# Generated by Django 5.0.6 on 2024-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_alter_insight_country_alter_insight_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='end_year',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='start_year',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
